name: weather_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  http: ^0.13.5
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.6.0
  provider: ^6.0.3
  geocoding: ^2.0.5
  objectbox: ^1.7.0
  objectbox_flutter_libs: ^1.7.0
  geolocator: ^9.0.2
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.16


dev_dependencies:
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
    image: assets/images/cloud.png
    color: '#000000'

flutter:
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/lang/
   
